version: '3.8'

services:
  my-shop-frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=9090
      - BACKEND_SERVICE=my-shop-backend
      - BACKEND_PORT=8080
    ports:
      - "9090:9090"
    depends_on:
      - my-shop-backend
    networks:
      - frontend

  my-shop-backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=my-shop-db
      - DB_PORT=3306
      - MYSQL_USER=root
      - MYSQL_DATABASE=test_nodejs
      - MYSQL_PASSWORD=
    depends_on:
      - my-shop-db
    networks:
      - backend
      - frontend

  my-shop-db:
    build:
      context: ./Backend/Mariadb
      dockerfile: Dockerfile
    restart: always
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
    ports:
      - "3306:3306"
    networks:
      - backend
 
networks:
  frontend:
  backend:
